select * from customer;

---total revenue generated by male vs female customers-----
select gender , sum(purchase_amount)
from customer
group by gender;

----Which customers used a discount but still spent more than the average purchase amount?---
select customer_id , purchase_amount 
from customer
where discount_applied = 'Yes' and purchase_amount > (select avg(purchase_amount) from customer);

-----Which are the top 5 products with the highest average review rating?-----
select item_purchased , avg(review_rating)::decimal(10,2)
from customer
group by item_purchased
order by avg(review_rating)DESC
limit 5;

------Compare the average Purchase Amounts between Standard and Express Shipping.-----
select shipping_type,
avg(purchase_amount)::decimal(10,2)
from customer
where shipping_type in ('Standard','Express')
group by shipping_type;

--Do subscribed customers spend more? Compare average spend and 
---total revenue between subscribers and non-subscribers.--
select subscription_status ,
count(customer_id) as total_customers, 
avg(purchase_amount):: decimal(10,2) as average_purchase_amount,
sum(purchase_amount) as total_revenue
from customer
group by subscription_status;

--------Which 5 products have the highest percentage of purchases with discounts applied?l----
select item_purchased , 
round(100 * sum(case when discount_applied = 'Yes' then 1 else 0 end)/count (*),2 )	as discount_rate
from customer
group by item_purchased
order by discount_rate DESC
limit 5;

--Segment customers into New, Returning, and Loyal based on their total
--number of previous purchases, and show the count of each segment.
with customer_type as (
select customer_id,previous_purchases,
case 
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'returning'
	else 'Loyal'
	end as customer_segment
from customer 
)

select customer_segment , count(*)
from customer_type
group by customer_segment;


------What are the top 3 most purchased products within each category?------
with item_count as(
select category,
item_purchased,
count(customer_id) as total_orders,
Row_number() over(partition by category order by count(customer_id) DESC) as item_rank
from customer
group by category,item_purchased
)

select 	item_rank, category,item_purchased, total_orders
from item_count
where item_rank <= 3; 

--Q9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
select subscription_status , count(customer_id)as repeat_buyers
from customer
where previous_purchases > 5
group by subscription_status;

----Q10 What is The revenue contribution of each age group ?----
select age_group, 
sum(purchase_amount),
round(sum(purchase_amount) * 100/(select sum(purchase_amount) from customer),2) as revenue_contr_percent
from customer
group by age_group
order by sum(purchase_amount) DESC;

